export const productIdeas = [
  "recipe subscription box for busy parents",
  "AI-powered language tutor for travelers",
  "marketplace for unused corporate event tickets",
  "personal finance app for freelancers",
  "smart home energy optimization system",
  "microlearning platform for healthcare professionals",
  "productivity tool for remote teams",
  "personalized fitness coaching app",
  "subscription service for sustainable clothing",
  "digital estate planning solution",
  "mental health chatbot for teens",
  "peer-to-peer pet sitting platform",
  "virtual reality meditation space",
  "on-demand handyman service app",
  "gamified recycling rewards program",
  "professional networking app for introverts",
  "digital nomad housing marketplace",
  "meal planning tool for dietary restrictions",
  "smart garden monitoring system",
  "skill-sharing platform for retirees",
] 